 table_catalog  |    table_schema    |              table_name               | table_type | self_referencing_column_name | reference_generation | user_defined_type_catalog | user_defined_type_schema | user_defined_type_name | is_insertable_into | is_typed | commit_action 
----------------+--------------------+---------------------------------------+------------+------------------------------+----------------------+---------------------------+--------------------------+------------------------+--------------------+----------+---------------
 d5qdkfnf0v3jg7 | public             | django_migrations                     | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | django_content_type                   | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | auth_permission                       | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | auth_group                            | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | auth_group_permissions                | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_type                               | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | auth_user                             | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | auth_user_groups                      | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | auth_user_user_permissions            | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | account_emailaddress                  | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_foreign_table                      | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | account_emailconfirmation             | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | django_admin_log                      | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_roles                              | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_settings                           | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | public             | courses_createdclasses                | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | courses_assignments                   | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_prepared_statements                | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_progress_vacuum               | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_subscription                       | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_attribute                          | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_proc                               | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_class                              | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_attrdef                            | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_constraint                         | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_inherits                           | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_index                              | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_operator                           | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_opfamily                           | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_opclass                            | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_am                                 | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_amop                               | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_amproc                             | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_language                           | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_largeobject_metadata               | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_aggregate                          | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_statistic_ext                      | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_rewrite                            | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_trigger                            | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_event_trigger                      | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_description                        | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_cast                               | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_progress_cluster              | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_progress_create_index         | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_progress_basebackup           | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_user_mappings                      | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | public             | courses_submission                    | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_enum                               | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_namespace                          | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_conversion                         | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_depend                             | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_database                           | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_db_role_setting                    | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_tablespace                         | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_auth_members                       | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_shdepend                           | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_shdescription                      | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_ts_config                          | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_ts_config_map                      | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_ts_dict                            | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_ts_parser                          | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_ts_template                        | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_extension                          | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_foreign_data_wrapper               | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_foreign_server                     | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_policy                             | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_replication_origin                 | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_default_acl                        | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_init_privs                         | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_seclabel                           | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_shseclabel                         | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_collation                          | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_partitioned_table                  | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_range                              | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_transform                          | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_sequence                           | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_publication                        | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_publication_rel                    | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_subscription_rel                   | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_group                              | VIEW       |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_user                               | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_policies                           | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_rules                              | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_views                              | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_tables                             | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_matviews                           | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_indexes                            | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_sequences                          | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stats                              | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stats_ext                          | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_publication_tables                 | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_locks                              | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_cursors                            | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_available_extensions               | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_available_extension_versions       | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_prepared_xacts                     | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_seclabels                          | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_statio_user_tables                 | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_all_indexes                   | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_timezone_abbrevs                   | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_timezone_names                     | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_sys_indexes                   | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_all_tables                    | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_xact_all_tables               | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_sys_tables                    | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_xact_sys_tables               | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_user_tables                   | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_xact_user_tables              | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_statio_all_tables                  | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_statio_sys_tables                  | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_user_indexes                  | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_statio_all_indexes                 | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_statio_sys_indexes                 | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_statio_user_indexes                | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_statio_all_sequences               | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_statio_sys_sequences               | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_statio_user_sequences              | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_activity                      | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_replication                   | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_slru                          | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_wal_receiver                  | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_subscription                  | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_ssl                           | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_gssapi                        | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_replication_slots                  | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_database                      | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_database_conflicts            | VIEW       |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_user_functions                | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_xact_user_functions           | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_archiver                      | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_bgwriter                      | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | pg_catalog         | pg_stat_progress_analyze              | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | columns                               | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | information_schema_catalog_name       | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | collations                            | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | applicable_roles                      | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | administrable_role_authorizations     | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | column_privileges                     | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | attributes                            | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | collation_character_set_applicability | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | character_sets                        | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | check_constraint_routine_usage        | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | check_constraints                     | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | column_column_usage                   | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | column_domain_usage                   | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | column_udt_usage                      | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | constraint_column_usage               | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | constraint_table_usage                | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | domain_constraints                    | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | domain_udt_usage                      | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | domains                               | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | enabled_roles                         | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | sql_implementation_info               | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | information_schema | key_column_usage                      | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | parameters                            | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | referential_constraints               | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | role_column_grants                    | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | routine_privileges                    | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | role_routine_grants                   | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | routines                              | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | schemata                              | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | tables                                | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | sequences                             | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | sql_sizing                            | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | information_schema | sql_features                          | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | information_schema | table_constraints                     | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | table_privileges                      | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | role_table_grants                     | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | udt_privileges                        | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | triggered_update_columns              | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | triggers                              | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | usage_privileges                      | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | role_udt_grants                       | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | role_usage_grants                     | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | user_defined_types                    | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | view_column_usage                     | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | view_routine_usage                    | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | public             | courses_submittedfiles                | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | information_schema | view_table_usage                      | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | foreign_tables                        | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | views                                 | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | data_type_privileges                  | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | element_types                         | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | column_options                        | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | foreign_data_wrapper_options          | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | user_mapping_options                  | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | foreign_data_wrappers                 | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | foreign_server_options                | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | public             | courses_notices                       | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | information_schema | foreign_servers                       | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | user_mappings                         | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | information_schema | foreign_table_options                 | VIEW       |                              |                      |                           |                          |                        | NO                 | NO       | 
 d5qdkfnf0v3jg7 | public             | courses_noticefile                    | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | courses_joinedclasses                 | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | courses_comments                      | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | courses_assignedpeers                 | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | django_session                        | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | socialaccount_socialaccount           | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | socialaccount_socialapp_sites         | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | django_site                           | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | socialaccount_socialtoken             | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
 d5qdkfnf0v3jg7 | public             | socialaccount_socialapp               | BASE TABLE |                              |                      |                           |                          |                        | YES                | NO       | 
(202 rows)

